// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATNmSQSY_o41Dppg2zkmcOf6FrT1jPfMo',
    appId: '1:180328689280:ios:a419b2c1054f86af438065',
    messagingSenderId: '180328689280',
    projectId: 'doorbell-18be3',
    storageBucket: 'doorbell-18be3.appspot.com',
    iosBundleId: 'personal.morgan.doorbell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATNmSQSY_o41Dppg2zkmcOf6FrT1jPfMo',
    appId: '1:180328689280:ios:853ed4848f504c20438065',
    messagingSenderId: '180328689280',
    projectId: 'doorbell-18be3',
    storageBucket: 'doorbell-18be3.appspot.com',
    iosBundleId: 'personal.morgan.doorbell.RunnerTests',
  );
}
